baseURL = 'https://jojoStar007.github.io/travelblog2026/'
languageCode = 'de-en-us-fr-es'
title = 'blogStolz'
theme = 'ananke'

[[menu.main]]
  identifier = "fotos"
  name = "Fotogalerie"
  url = "/fotos/"
  weight = 20  # Bestimmt die Position (je höher, desto weiter rechts)

[caches]
  [caches.images]
    dir = ':cacheDir/images'


# Standard-Sprache (falls nichts angegeben ist)
defaultContentLanguage = "de"

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 1
    title = "Mein Reiseblog" # Titel auf Deutsch
    # Dein deutsches Menü
    [[languages.de.menu.main]]
      identifier = "fotos"
      name = "Fotogalerie"
      pageRef = "fotos"
      weight = 20

  [languages.en]
    languageName = "English"
    weight = 2
    title = "My Travel Blog" # Titel auf Englisch
    # Dein englisches Menü
    [[languages.en.menu.main]]
      identifier = "fotos"
      name = "Photo Gallery"
      pageRef = "fotos"
      weight = 20


[languages.fr]
    languageName = "Francais"
    weight = 3
    title = "Mon Blog de Voyage"
    [[languages.fr.menu.main]]
      identifier = "fotos"
      name = "Galerie Photos"
      pageRef = "fotos"
      weight = 20


[languages.es]
    languageName = "Espanol"
    weight = 4
    title = "Mi Blog de Viajes"
    [[languages.es.menu.main]]
      identifier = "fotos"
      name = "Galería de Fotos"
      pageRef = "fotos"
      weight = 20
